steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'echo $$github_repo_read > etc/secrets/github_token.txt; echo $$docs_username > etc/secrets/docs_username.txt; echo $$docs_password > etc/secrets/docs_password.txt']
    secretEnv: ['github_repo_read', 'docs_username', 'docs_password']
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'echo $_MODULES | tr "," "\n" > etc/modules.txt']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - 'VANITY_HOST=$_VANITY_HOST'
      - '--build-arg'
      - 'USE_GCP_SECRETS=true'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--timeout=600s'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/github_repo_read/versions/1'
    env: 'github_repo_read'
  - versionName: 'projects/$PROJECT_ID/secrets/docs_username/versions/1'
    env: 'docs_username'
  - versionName: 'projects/$PROJECT_ID/secrets/docs_password/versions/1'
    env: 'docs_password'
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'
